### ISSUE TITLE
Annoying Bar in Pet Battles

### ISSUE THREAD

**Issue by Imiona** [axc450/pbs#16]
Hey

I have this Bar in my Pet Battles under the Health Frame, how can i get rid of it, it does nothing.

![Wow 2022-11-18 18-04-28](https://user-images.githubusercontent.com/11210717/202761272-07b1cbfe-513a-467b-a04c-57ae58456ad0.png)

**Comment by axc450** [comment]
I think this is because the addon creates that even if you are not using the default UI (ElvUI in this case). I can look at having it not create this bar if ElvUI is being used

**Comment by ostjaevel** [comment]
Posted a temporary fix if you want to fix it yourself until axc450 finds a way to hide it when we use ElvUI (same fix as was posted in the previous iteration, just reposted for visibility).
https://www.curseforge.com/wow/addons/pet-battle-scripts?comment=54

**Comment by axc450** [comment]
Thanks - I think its the same changes but with an ElvUI check before 😄 
I will see if I can find to time to implement this

**Comment by Imiona** [comment]
> Posted a temporary fix if you want to fix it yourself until axc450 finds a way to hide it when we use ElvUI (same fix as was posted in the previous iteration, just reposted for visibility). https://www.curseforge.com/wow/addons/pet-battle-scripts?comment=54

Works, thank you !

**Comment by axc450** [comment]
Reopening this just to track the actual fix in the addon

**Comment by Rhinomer** [comment]
Oh yes I would be super happy if this annoying bar would be gone after years. 🙏

**Comment by bloerwald** [comment]
This is fixed with #26 (in current release) and will be fixed-fixed with #31.
