### ISSUE TITLE
self.active "Not found command"

### ISSUE THREAD

**Issue by VanyaMornie** [axc450/pbs#20]
Script imported from XuFu - nil issues prior, now reports

"Found error: Invalid Condition: 'self(#2).active' (Not found cmd 'self.active')

Screenshot attached

![image](https://user-images.githubusercontent.com/10843362/206842926-da4195c4-4d45-40b4-b8f0-729a5c464611.png)

**Comment by DravenSA** [comment]
Any news on this? I have similar error

**Comment by darodriguesPT** [comment]
The Add-On hasn't been updated for some time, and someone created a fork for 10.0 called "Pet Battle Scripts" that replaces both "TDBattlePetScripts" and "TDBattlePetScripts Rematch". Not sure if the original author will come back to support the main Add-Ons. It was a great work he/she has done over the years! :)

**Comment by cgsub** [comment]
I have had this error popping for a while on some use command. 
After a while it proved to be related to an extra space separator causing the problem.

**Comment by bloerwald** [comment]
Can't reproduce with only the add-on installed. Please reopen issue if the issue persists after making sure only exactly one and the new addon version is installed.
