### ISSUE TITLE
Feature Request: More options for queue prioritization 

### ISSUE THREAD

**Issue by LyaVanLou** [axc450/pbs#21]
Hey there, 
I think it'd be really nice to have some more options for which pets get prioritized in the leveling queue. 

The two I'm specifically missing are: 
- Pets in a team first
- Pets with notes first

**Comment by bloerwald** [comment]
Hi,
you seem to have mixed up addons. The Leveling Queue feature is part of Rematch, not this Addon. You might want to ask for this feature over at https://www.curseforge.com/wow/addons/rematch instead.
