### ISSUE TITLE
Script Selector Button always showing?!

### ISSUE THREAD

**Issue by mrmax3000** [axc450/pbs#22]
Why do I always have to press the button to select the rematch script? Is this not saved or is there a Key for it? that's really annoying when leveling new pets.

**Comment by bloerwald** [comment]
I'm sorry, I can't reproduce this issue. Can you give more detail in what steps you take and what you click and where it differs from your expectation? Do you have other scripts that match the current enemy offered in the script selector?

**Comment by mrmax3000** [comment]
oh hi, the Problem sloved itself by re istalling petbattlescript and rematch. i deleted all addons + wft files, and after the new installation it works like a charm.
thx and bb :)
