### ISSUE TITLE
 Can't this box come out?

### ISSUE THREAD

**Issue by fodxod** [axc450/pbs#23]
![111](https://user-images.githubusercontent.com/123018511/213275855-e3f968b4-06f0-4b73-93bd-4e15fac014d0.png)

**Comment by bloerwald** [comment]
Not happening without extra addons installed. If issue persists, please try disabling half of your addons to see whether the issue persists. If disabling that half removed the issue, please re-enable and disable the other half. Repeat disabling half of it until you find the add-on causing it and re-open the issue with the add-on or addons causing the issue.
