### ISSUE TITLE
i tried this addon today and it keeps not working. 

### ISSUE THREAD

**Issue by Kosterc1** [axc450/pbs#24]
https://prnt.sc/SM1pps_Cyup3 is what i already notice in curseforge. latest version. Did it break when we went over to 10.0.5? not sure but it is totally not working.

**Comment by bloerwald** [comment]
Are you getting any errors? In what way is it not working? Do you have only this add-on installed or also the old one or the old rematch one?

**Comment by Kosterc1** [comment]
So I reinstalled rematch and it started working. But it was the same
version of rematch. Still the warning ⚠️.  No errors it just didn't show up
in game. While that char only had those 2 add-ons.

**Comment by bloerwald** [comment]
Tested myself today on retail servers, works perfectly fine, please open more specific issue if issue persists.
