### ISSUE TITLE
Auto Button Not Working

### ISSUE THREAD

**Issue by LadyDominia** [axc450/pbs#25]
There was previous functionality where the Auto Button would be a single press key that would step through the script. This functionality is either missing or not working. Is there any update on whether this functionality will be fixed or re-implemented? If this can no longer be done due to changes to Blizzard's API or something, can we please get that statement added to the addon description in CurseForge?

**Comment by bloerwald** [comment]
I have just tested myself on retail servers and the auto battle button works fine both when clicking and pressing the bound key.

I'm not sure what's broken here. What version do you have installed? You did test it on retail or PTR? Is the key by chance bound to anything else as well? Are there any Lua errors? Is there a script selected to run? What does pressing `Test` in the script editor result in?
