### ISSUE TITLE
Latest version.

### ISSUE THREAD

**Issue by griddark** [axc450/pbs#38]
1x AceLocale-3.0-6: PetBattleScripts: Missing entry for 'OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE_SOUND'
[string "@tdBattlePetScript/UI/Options.lua"]:57: in function `InitOptions'
[string "@tdBattlePetScript/UI/Options.lua"]:12: in function <tdBattlePetScript/UI/Options.lua:11>

**Comment by Ookami313** [comment]
Adding to the above error, I'm receiving two errors with the same Missing entry statement. Thanks.

1x AceLocale-3.0-6: PetBattleScripts: Missing entry for 'OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE_SOUND'
[string "@tdBattlePetScript/UI/Options.lua"]:57: in function `InitOptions'
[string "@tdBattlePetScript/UI/Options.lua"]:12: in function <tdBattlePetScript/UI/Options.lua:11>
[string "=[C]"]: ?
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:545: in function `UIParentLoadAddOn'
[string "@Rarity/Core/Collections.lua"]:63: in function `ScanToys'
[string "@Rarity/Core/Collections.lua"]:283: in function `ScanExistingItems'
[string "@Rarity/Core.lua"]:174: in function `DoEnable'
...
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:545: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:684: in function `TimeManager_LoadUI'
[string "@FrameXML/UIParent.lua"]:1541: in function <FrameXML/UIParent.lua:1421>
[string "=[C]"]: ?

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:213
 defaultModuleLibraries = <table> {
 }
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 baseName = "tdBattlePetScript"
 enabledState = true
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 OnEnable = <function> defined @tdBattlePetScript/UI/Options.lua:11
 moduleName = "Options"
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleState = true
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 IterateModules = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 name = "PetBattleScripts_Options"
 InitOptions = <function> defined @tdBattlePetScript/UI/Options.lua:15
 IsEnabled = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 SetDefaultModuleState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:383
 DisableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:346
}
(*temporary) = <table> {
 type = "group"
}
(*temporary) = <table> {
 newLine1 = <table> {
 }
 hideMinimap = <table> {
 }
 newLine2 = <table> {
 }
 notifyButtonActive = <table> {
 }
 autoButtonHotKey = <table> {
 }
}
(*temporary) = <table> {
 type = "select"
 order = 5
}
(*temporary) = <table> {
 TOGGLE_SCRIPT_MANAGER = "Toggle script manager"
 Export = "Export"
 Download = "Download"
 PLUGINBASE_TEAM_ENEMY = "Enemy"
 NOTES = "This script selector will be bound to the Rematch team."
 OPTION_SETTINGS_AUTOBUTTON_HOTKEY = "Autobattle Hotkey"
 OPTION_SCRIPTSELECTOR_NOTES = "Here you can manage the script selector is open, and its priority."
 Auto = "Autobattle"
 OPTION_SETTINGS_AUTO_SELECT_SCRIPT_ONLY_ONE = "Automatically select script by script selector priority"
 PLUGINBASE_TEAM_ALLY = "Ally"
 OPTION_GENERAL_NOTES = "Here are some general Settings."
 No script = "No script"
 IMPORT_REINPUT_TEXT = "Re-edit"
 TOGGLE_SCRIPT_SELECTOR = "Toggle script selector"
 PLUGINFIRSTENEMY_NOTIFY = "Discover that you've previously used the modified version of tdBattlePetScript and have migrated some of the scripts for the modified Base Selector to firstEnemy Selector."
 OPTION_SETTINGS_HIDE_SELECTOR_NO_SCRIPT = "The script selector is not displayed when there is no script"
 OPTION_SETTINGS_HIDE_MINIMAP_TOOLTIP = "Changing this setting requires reloading the UI. Do you want to continue?"
 Script manager = "Script manager"
 SCRIPT_EDITOR_LABEL_TOGGLE_EXTRA = "Toggle extension information editor"
 OPTION_SETTINGS_LOCK_SCRIPT_SELECTOR = "Lock the script selector"
 PLUGINALLINONE_TITLE = "All in one"
 Don't ask me = "Don't ask me"
 IMPORT_CHOOSE_PLUGIN = "Select the script selector..."
 NO_TEAM_FOR_SCRIPT = "No team matches this script"
 PLUGINBASE_TITLE = "Base"
 Installed = "Installed"
 TITLE = "Rematch"
 WRITE_SCRIPT = "Write script"
 Font size = "Font size"
 PLUGINBASE_NOTES = "This script selector matches ally and enemy."
 SCRIPT_SELECTOR_NOT_MATCH = "No script selector matches to the current battle"
 Create script = "Create script"
 OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE = "OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE

1x AceLocale-3.0-6: PetBattleScripts: Missing entry for 'OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE'
[string "@tdBattlePetScript/UI/Options.lua"]:46: in function `InitOptions'
[string "@tdBattlePetScript/UI/Options.lua"]:12: in function <tdBattlePetScript/UI/Options.lua:11>
[string "=[C]"]: ?
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:545: in function `UIParentLoadAddOn'
[string "@Rarity/Core/Collections.lua"]:63: in function `ScanToys'
[string "@Rarity/Core/Collections.lua"]:283: in function `ScanExistingItems'
[string "@Rarity/Core.lua"]:174: in function `DoEnable'
...
[string "@PetTracker/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...dOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:545: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:684: in function `TimeManager_LoadUI'
[string "@FrameXML/UIParent.lua"]:1541: in function <FrameXML/UIParent.lua:1421>
[string "=[C]"]: ?

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:213
 defaultModuleLibraries = <table> {
 }
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 baseName = "tdBattlePetScript"
 enabledState = true
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 OnEnable = <function> defined @tdBattlePetScript/UI/Options.lua:11
 moduleName = "Options"
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleState = true
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 IterateModules = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 name = "PetBattleScripts_Options"
 InitOptions = <function> defined @tdBattlePetScript/UI/Options.lua:15
 IsEnabled = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 SetDefaultModuleState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:383
 DisableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:346
}
(*temporary) = <table> {
 type = "group"
}
(*temporary) = <table> {
 newLine1 = <table> {
 }
 hideMinimap = <table> {
 }
 newLine2 = <table> {
 }
 autoButtonHotKey = <table> {
 }
}
(*temporary) = <table> {
 type = "toggle"
 order = 4
}
(*temporary) = <table> {
 TOGGLE_SCRIPT_MANAGER = "Toggle script manager"
 Export = "Export"
 Download = "Download"
 PLUGINBASE_TEAM_ENEMY = "Enemy"
 NOTES = "This script selector will be bound to the Rematch team."
 OPTION_SETTINGS_AUTOBUTTON_HOTKEY = "Autobattle Hotkey"
 OPTION_SCRIPTSELECTOR_NOTES = "Here you can manage the script selector is open, and its priority."
 Auto = "Autobattle"
 OPTION_SETTINGS_AUTO_SELECT_SCRIPT_ONLY_ONE = "Automatically select script by script selector priority"
 PLUGINBASE_TEAM_ALLY = "Ally"
 OPTION_GENERAL_NOTES = "Here are some general Settings."
 No script = "No script"
 IMPORT_REINPUT_TEXT = "Re-edit"
 TOGGLE_SCRIPT_SELECTOR = "Toggle script selector"
 PLUGINFIRSTENEMY_NOTIFY = "Discover that you've previously used the modified version of tdBattlePetScript and have migrated some of the scripts for the modified Base Selector to firstEnemy Selector."
 OPTION_SETTINGS_HIDE_SELECTOR_NO_SCRIPT = "The script selector is not displayed when there is no script"
 OPTION_SETTINGS_HIDE_MINIMAP_TOOLTIP = "Changing this setting requires reloading the UI. Do you want to continue?"
 Script manager = "Script manager"
 SCRIPT_EDITOR_LABEL_TOGGLE_EXTRA = "Toggle extension information editor"
 OPTION_SETTINGS_LOCK_SCRIPT_SELECTOR = "Lock the script selector"
 PLUGINALLINONE_TITLE = "All in one"
 Don't ask me = "Don't ask me"
 IMPORT_CHOOSE_PLUGIN = "Select the script selector..."
 NO_TEAM_FOR_SCRIPT = "No team matches this script"
 PLUGINBASE_TITLE = "Base"
 Installed = "Installed"
 TITLE = "Rematch"
 WRITE_SCRIPT = "Write script"
 Font size = "Font size"
 PLUGINBASE_NOTES = "This script selector matches ally and enemy."
 SCRIPT_SELECTOR_NOT_MATCH = "No script selector matches to the current battle"
 Create script = "Create script"
 OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE = "OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE"
 PLUGINFIRSTENEMY_NOTES = "This s

**Comment by teelolws** [comment]
`OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE_SOUND` doesn't have an entry at https://legacy.curseforge.com/wow/addons/pet-battle-scripts/localization/languages/92/phrases#424264

Idk if its supposed to get the translation from somewhere else? Bug was added in https://github.com/axc450/pbs/commit/9f04496879f42d57021f21083e5b82cc23f54a9c#diff-f2526a046ffcf749229c61fb9293c662aab911779013d78a8b9070b94bf334adR57

**Comment by fraerie** [comment]
confirming I'm also seeing both these errors

**Comment by Roneasaurus** [comment]
same for me. 

6x AceLocale-3.0-6: PetBattleScripts: Missing entry for 'OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE_SOUND'
[string "@tdBattlePetScript/UI/Options.lua"]:57: in function `InitOptions'
[string "@tdBattlePetScript/UI/Options.lua"]:12: in function <tdBattlePetScript/UI/Options.lua:11>
[string "=[C]"]: ?
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:545: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:754: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:213
 defaultModuleLibraries = <table> {
 }
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 baseName = "tdBattlePetScript"
 enabledState = true
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 OnEnable = <function> defined @tdBattlePetScript/UI/Options.lua:11
 moduleName = "Options"
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleState = true
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 IterateModules = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 name = "PetBattleScripts_Options"
 InitOptions = <function> defined @tdBattlePetScript/UI/Options.lua:15
 IsEnabled = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 SetDefaultModuleState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:383
 DisableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:346
}
(*temporary) = <table> {
 type = "group"
}
(*temporary) = <table> {
 newLine1 = <table> {
 }
 hideMinimap = <table> {
 }
 newLine2 = <table> {
 }
 notifyButtonActive = <table> {
 }
 autoButtonHotKey = <table> {
 }
}
(*temporary) = <table> {
 type = "select"
 order = 5
}
(*temporary) = <table> {
 TOGGLE_SCRIPT_MANAGER = "Toggle script manager"
 Export = "Export"
 Download = "Download"
 PLUGINBASE_TEAM_ENEMY = "Enemy"
 NOTES = "This script selector will be bound to the Rematch team."
 OPTION_SETTINGS_AUTOBUTTON_HOTKEY = "Autobattle Hotkey"
 OPTION_SCRIPTSELECTOR_NOTES = "Here you can manage the script selector is open, and its priority."
 Auto = "Autobattle"
 OPTION_SETTINGS_AUTO_SELECT_SCRIPT_ONLY_ONE = "Automatically select script by script selector priority"
 PLUGINBASE_TEAM_ALLY = "Ally"
 OPTION_GENERAL_NOTES = "Here are some general Settings."
 No script = "No script"
 IMPORT_REINPUT_TEXT = "Re-edit"
 TOGGLE_SCRIPT_SELECTOR = "Toggle script selector"
 PLUGINFIRSTENEMY_NOTIFY = "Discover that you've previously used the modified version of tdBattlePetScript and have migrated some of the scripts for the modified Base Selector to firstEnemy Selector."
 OPTION_SETTINGS_HIDE_SELECTOR_NO_SCRIPT = "The script selector is not displayed when there is no script"
 OPTION_SETTINGS_HIDE_MINIMAP_TOOLTIP = "Changing this setting requires reloading the UI. Do you want to continue?"
 Script manager = "Script manager"
 SCRIPT_EDITOR_LABEL_TOGGLE_EXTRA = "Toggle extension information editor"
 OPTION_SETTINGS_LOCK_SCRIPT_SELECTOR = "Lock the script selector"
 PLUGINALLINONE_TITLE = "All in one"
 Don't ask me = "Don't ask me"
 IMPORT_CHOOSE_PLUGIN = "Select the script selector..."
 NO_TEAM_FOR_SCRIPT = "No team matches this script"
 PLUGINBASE_TITLE = "Base"
 Installed = "Installed"
 TITLE = "Rematch"
 WRITE_SCRIPT = "Write script"
 Font size = "Font size"
 PLUGINBASE_NOTES = "This script selector matches ally and enemy."
 SCRIPT_SELECTOR_NOT_MATCH = "No script selector matches to the current battle"
 Create script = "Create script"
 OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE = "OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE

**Comment by ostjaevel** [comment]
Tempfix until the addon author adds in the proper translations:
Add the following to the translation file of your choice (eg .\World of Warcraft\_retail_\Interface\AddOns\tdBattlePetScript\Localization\enUS.lua).

L["OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE"] = "Play sound when hotkey is pressed"
L["OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE_SOUND"] = "Hotkey notification sound"

**Comment by bloerwald** [comment]
Thanks for the reports, the issue is as @teelolws said. We are aware of it and will push a new release with the fix soon. Sadly only @axc450 has permission to change the translations, so we need to wait for them.

In the meantime, use the workaround @ostjaevel suggested which I have prepared 
[here](https://github.com/axc450/pbs/files/11396976/PetBattleScripts-v1.7-hackfix.zip).

A release with the fix will follow, hopefully today.

**Comment by bloerwald** [comment]
A new version (1.7.5) with the fix was published. It should show up in your addon installers soonish.
