### ISSUE TITLE
Errors since patch

### ISSUE THREAD

**Issue by sinjinns** [axc450/pbs#39]
I've been getting these pretty often, especially the first one

22x ...PetTracker/libs/Sushi-3.1-5/classes/drops/Dropdown.lua:148: calling 'IsMouseOver' on bad self (Usage: local isMouseOver = self:IsMouseOver([offsetTop, offsetBottom, offsetLeft, offsetRight]))
[string "=[C]"]: in function `IsMouseOver'
[string "@PetTracker/libs/Sushi-3.1-5/classes/drops/Dropdown.lua"]:148: in function <...PetTracker/libs/Sushi-3.1/classes/drops/Dropdown.lua:147>
[string "@PetTracker/libs/Sushi-3.1-5/classes/drops/Dropdown.lua"]:153: in function <...PetTracker/libs/Sushi-3.1/classes/drops/Dropdown.lua:147>
[string "=(tail call)"]: ?
[string "@PetTracker/libs/Sushi-3.1-5/classes/drops/Dropdown.lua"]:93: in function <...PetTracker/libs/Sushi-3.1/classes/drops/Dropdown.lua:92>

3x [ADDON_ACTION_BLOCKED] AddOn 'PetTracker' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML/LFGList.lua"]:3524: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML/LFGList.lua"]:2597: in function <FrameXML/LFGList.lua:2594>

**Comment by bloerwald** [comment]
You seem to be confusing addons. This is the battle scripts one, you’re having issues with the tracking one. We have no influence on that, sadly.

**Comment by sinjinns** [comment]
oops, I must have checked the wrong addon on curseforge and followed the link here thinking it was the right place. Sorry!
