### ISSUE TITLE
Test button in script editor

### ISSUE THREAD

**Issue by erigul** [axc450/pbs#4]
Add an Evaluation/Test button in the script editor that would run the script and let the user know which action would have been carried out, without actually performing the action.

Would often be useful when writing scripts to check that the edit is doing what you'd want (and avoid facepalm moments where it **really** doesn't do what you want, and the fight moves on to the next turn with an unwanted action)

**Comment by bloerwald** [comment]
Note that there already is a `test()` action. It isn't the best UX, but you can transform
```
use(#1) [ enemy.dead ]
use(#2) 
```
to
```
test(use(#1)) [ enemy.dead ]
test(use(#2))
```
and will get the wanted behaviour. 

I suggest we would do the same transformation under the hood, if we add such a button.

**Comment by axc450** [comment]
I have added some UX around this and it should be available in `v1.3`:

![image](https://user-images.githubusercontent.com/30942843/201479946-e8cedf4e-48a5-4fc1-b34c-6f9814d6930b.png)

**Comment by erigul** [comment]
I had a quick test with it and I don't think it quite works. Looks like it only inspects the conditions, not if the actual action is possible even if the condition is met? (i.e. spell on cooldown, this pet doesn't have the spell, the pet you try to swap to is already active etc)

**Comment by axc450** [comment]
Yeah, I didnt release `v1.3` yet because I was aware of some issues but I had to head out today so pushed what I had time to do.
