### ISSUE TITLE
Can't hide minimap button and showing icon on Chocolatebar.

### ISSUE THREAD

**Issue by TreizeEU** [axc450/pbs#40]
Hello.

I recently installed this addon to make pet battling a bit less tedious, but I found an issue:

When I wanted to show the icon on my ChocolateBar addon, but also hide the minimap icon. If I try, it will make ChocolateBar to not register this addon at all, thus not showing its icon on the bar.

Any ideas?

**Comment by bloerwald** [comment]
This is fixed in #32, which will hopefully be merged soon.

In the meantime, you can manually replicate the change by 

- open `UI/Minimap.lua`
- in `function Minimap:OnInitialize()`, remove 
```
if Addon:GetSetting('hideMinimap') then
    return
end
```
- in the same function, at the very bottom add `self:Refresh()`.

**Comment by TreizeEU** [comment]
Am I doing it correctly? Or where do you want me to add the "self:Refresh()" line?

`function Minimap:OnInitialize()

    local LDB = LibStub('LibDataBroker-1.1')

    local function HideTooltip()
        GameTooltip:Hide()

        if LibDBIcon.tooltip then
            LibDBIcon.tooltip:Hide()
        self:Refresh()
        end
    end`

**Comment by bloerwald** [comment]
Just use this file: https://gist.github.com/bloerwald/b5a631033b437c1f12712a38e3d797f1

**Comment by TreizeEU** [comment]
Cheers. I copied the raw text from that link and it seems to let me do what I want with the minimap icon and chocolatebar icon. :D
