### ISSUE TITLE
Errors recently

### ISSUE THREAD

**Issue by sinjinns** [axc450/pbs#46]
Been getting these recently, not sure when it started, maybe weekly reset on the 9th?

19x tdBattlePetScript/Rematch/UI.lua:53: attempt to call method 'GetMenu' (a nil value)
[string "@tdBattlePetScript/Rematch/UI.lua"]:53: in function <tdBattlePetScript/Rematch/UI.lua:52>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:516>
[string "=(tail call)"]: ?
[string "@tdBattlePetScript/Core/Manager/PluginManager.lua"]:149: in function `LoadPlugins'
[string "@tdBattlePetScript/Core/Manager/PluginManager.lua"]:33: in function <...Ons/tdBattlePetScript/Core/Manager/PluginManager.lua:32>

**Comment by sinjinns** [comment]
I have, I'm using Rematch 5_0_0_beta_10, I'm not sure I understand what they're talking about in the post you linked. Is the error related to storing scripts? isn't that the whole point of pet battle scripts?

**Comment by bloerwald** [comment]
This addon currently does not support Rematch 5, only Rematch 4.
