### ISSUE TITLE
LUA error PetBattle Script 1.8

### ISSUE THREAD

**Issue by fraerie** [axc450/pbs#48]
LUA error on load in

4x tdBattlePetScript/Rematch/UI.lua:53: attempt to call method 'GetMenu' (a nil value)
[string "@tdBattlePetScript/Rematch/UI.lua"]:53: in function <tdBattlePetScript/Rematch/UI.lua:52>
[string "=[C]"]: ?
[string "@Ailo/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...rfaceAilo/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ailo/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function <...rfaceAilo/Libs/AceAddon-3.0/AceAddon-3.0.lua:516>
[string "=(tail call)"]: ?
[string "@tdBattlePetScript/Core/Manager/PluginManager.lua"]:149: in function `LoadPlugins'
[string "@tdBattlePetScript/Core/Manager/PluginManager.lua"]:33: in function <...Ons/tdBattlePetScript/Core/Manager/PluginManager.lua:32>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ailo/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Ailo/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Ailo/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @Ailo/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Ailo/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Ailo/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHook = <function> defined @Ailo/Libs/AceHook-3.0/AceHook-3.0.lua:335
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @Ailo/Libs/AceHook-3.0/AceHook-3.0.lua:394
 IterateKeys = <function> defined @tdBattlePetScript/Rematch/Addon.lua:24
 hooks = <table> {
 }
 _title = "Rematch"
 SetDefaultModulePrototype = <function> defined @Ailo/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 baseName = "tdBattlePetScript"
 OnImport = <function> defined @tdBattlePetScript/Rematch/UI.lua:256
 OnExport = <function> defined @tdBattlePetScript/Rematch/UI.lua:249
 name = "PetBattleScripts_PluginManager_Rematch"
 _icon = "Interface\Icons\Icon_petfamily_dragon"
 IsEnabled = <function> defined @Ailo/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 OnTooltipFormatting = <function> defined @tdBattlePetScript/Rematch/Addon.lua:36
 DisableModule = <function> defined @Ailo/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 NewClass = <function> defined @tdBattlePetScript/Libs/tdGUI/Libs/LibClass-2.0/Class-2.0.lua:349
 OnDisable = <function> defined @tdBattlePetScript/Rematch/UI.lua:237
 OnEnable = <function> defined @tdBattlePetScript/Rematch/UI.lua:52
 GetTitleByKey = <function> defined @tdBattlePetScript/Rematch/Addon.lua:32
 RegisterMessage = <function> defined @Ailo/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Ailo/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 FindMenuItem = <function> defined @tdBattlePetScript/Rematch/UI.lua:241
 GetCurrentKey = <function> defined @tdBattlePetScript/Rematch/Addon.lua:20
 IsHooked = <function> defined @Ailo/Libs/AceHook-3.0/AceHook-3.0.lua:492
 OnInitialize = <function> defined @tdBattlePetScript/Rematch/Addon.lua:13
 GetClass = <function> defined @tdBattlePetScript/Libs/tdGUI/Libs/LibClass-2.0/Class-2.0.lua:359
 IsModule = <function> defined @Ailo/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 _notes = "This script selector will be bound to the Rematch team."
 SetDefaultModuleState = <function> defined @Ailo/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 SendMessage = <function> defined @Ailo/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 UnhookAll = <function> defined @Ailo/Libs/AceHook-3.0/AceHook-3.0.lua:476
 SetEnabledState = <function> defined @Ailo/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Ailo/Libs/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 Unhook = <function> defined @Ailo/Libs/AceHook-3.0/AceHook-3.0.lua:417
 RegisterEvent = <function> defined @Ailo/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @Ailo/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 SecureHookScript = <function> defined @Ailo/Libs/AceHook-3.0/AceHook-3.0.lua:409
 HookScript = <function> defined @Ailo/Libs/AceHook-3.0/AceHook-3.0.lua:365
 UnregisterAllEvents = <function> defined @Ailo/Libs/CallbackHandler-1.0/CallbackH

**Comment by bloerwald** [comment]
This addon currently does not support Rematch 5, only Rematch 4. See #45.
