### ISSUE TITLE
bug get menu line 53

### ISSUE THREAD

**Issue by Addonman** [axc450/pbs#54]
Message: Interface/AddOns/tdBattlePetScript/Rematch/UI.lua line 53:
   attempt to call method 'GetMenu' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/tdBattlePetScript/Rematch/UI.lua"]:53:
      Interface/AddOns/tdBattlePetScript/Rematch/UI.lua:52
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66:
      ...AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:61
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523:
      ...AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:516
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/tdBattlePetScript/Core/Manager/PluginManager.lua"]:149: LoadPlugins()
   [string "@Interface/AddOns/tdBattlePetScript/Core/Manager/PluginManager.lua"]:33:
      ...Ons/tdBattlePetScript/Core/Manager/PluginManager.lua:32
Locals:
(*temporary) = <function> defined =[C]:-1

**Comment by bloerwald** [comment]
We do not support the rematch 5 beta. See #45
