### ISSUE TITLE
Auto Summon

### ISSUE THREAD

**Issue by RangerTure** [axc450/pbs#55]
I do not want pets to be Autosummoned when I change teams. tdbattlescript dealt with this. Can't find any option to turn this off

**Comment by bloerwald** [comment]
Are you sure you remember that right? This addon can’t even load teams, so it doesn’t influence summoning them either.

**Comment by RangerTure** [comment]
> Are you sure you remember that right? This addon can’t even load teams, so it doesn’t influence summoning them either.

You are correct, that option comes from Rematch. I was under the weather this past weekend and mistook where the options came from. Thanks for replying
