### ISSUE TITLE
Pet Battle Script bug

### ISSUE THREAD

**Issue by rambutanMan** [axc450/pbs#73]
43x tdBattlePetScript/Rematch/Addon.lua:214: attempt to index field '?' (a function value)
[string "@tdBattlePetScript/Rematch/Addon.lua"]:214: in function `GetTitleByKey'
[string "@tdBattlePetScript/UI/Import.lua"]:265: in function `menuTable'
[string "@tdBattlePetScript/Libs/tdGUI/Widget/Dropdown.lua"]:124: in function <...Ons/tdBattlePetScript/Libs/tdGUI/Widget/Dropdown.lua:120>
[string "=[C]"]: in function `Click'
[string "@tdBattlePetScript/Libs/tdGUI/Widget/Dropdown.lua"]:41: in function <...Ons/tdBattlePetScript/Libs/tdGUI/Widget/Dropdown.lua:40>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 UnhookAll = <function> defined @EasyFrames/Libs/AceHook-3.0/AceHook-3.0.lua:476
 Enable = <function> defined @Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 SecureHookScript = <function> defined @EasyFrames/Libs/AceHook-3.0/AceHook-3.0.lua:409
 EnableModule = <function> defined @Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 _icon = "Interface\AddOns\Rematch\Textures\icon"
 SecureHook = <function> defined @EasyFrames/Libs/AceHook-3.0/AceHook-3.0.lua:335
 defaultModuleLibraries = <table> {
 }
 hooks = <table> {
 }
 _title = "Rematch"
 baseName = "tdBattlePetScript"
 RawHookScript = <function> defined @EasyFrames/Libs/AceHook-3.0/AceHook-3.0.lua:394
 TeardownUI = <function> defined @tdBattlePetScript/Rematch/UI.lua:212
 SendMessage = <function> defined @Bazooka/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 UpdateDBRematch4To5 = <function> defined @tdBattlePetScript/Rematch/Addon.lua:325
 ResetEverything = <function> defined @tdBattlePetScript/Rematch/Addon.lua:318
 SetDefaultModulePrototype = <function> defined @Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 OnImportContinuation = <function> defined @tdBattlePetScript/Rematch/Addon.lua:305
 OnImport = <function> defined @tdBattlePetScript/Rematch/Addon.lua:284
 OnExport = <function> defined @tdBattlePetScript/Rematch/Addon.lua:267
 name = "PetBattleScripts_PluginManager_Rematch"
 OnExportImpl = <function> defined @tdBattlePetScript/Rematch/Addon.lua:256
 IsEnabled = <function> defined @Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 OnTooltipFormatting = <function> defined @tdBattlePetScript/Rematch/Addon.lua:220
 DisableModule = <function> defined @Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 NewClass = <function> defined @tdBattlePetScript/Libs/tdGUI/Libs/LibClass-2.0/Class-2.0.lua:349
 GetTitleByKey = <function> defined @tdBattlePetScript/Rematch/Addon.lua:210
 IterateKeys = <function> defined @tdBattlePetScript/Rematch/Addon.lua:196
 GetCurrentKey = <function> defined @tdBattlePetScript/Rematch/Addon.lua:186
 RegisterMessage = <function> defined @Bazooka/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Bazooka/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 OnDisable = <function> defined @tdBattlePetScript/Rematch/Addon.lua:167
 OnEnable = <function> defined @tdBattlePetScript/Rematch/Addon.lua:25
 IsHooked = <function> defined @EasyFrames/Libs/AceHook-3.0/AceHook-3.0.lua:492
 OnInitialize = <function> defined @tdBattlePetScript/Rematch/Addon.lua:14
 GetClass = <function> defined @tdBattlePetScript/Libs/tdGUI/Libs/LibClass-2.0/Class-2.0.lua:359
 IsModule = <function> defined @Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:213
 _notes = "This script selector will be bound to the Rematch team."
 SetDefaultModuleState = <function> defined @Bazooka/libs/Ace3/AceAddon-3.0/AceAddon-3.0.lua:383
 SetupUI = <function> defined @tdBattlePetScript/Rematch/UI.lua:49
 updateFrames = <function> defined @tdBattlePetScript/Rematch/UI.lua:64
 SetEnabledStat

**Comment by bloerwald** [comment]
Which version of the addon and which version of Rematch are you using?

**Comment by rambutanMan** [comment]
11/26/2023 version 5.0.3

**Comment by bloerwald** [comment]
You're the first person I know to use the import/export functions, congratulations

It appears there is inconsistency between rematch and your scripts. this really shouldn't happen, but we seem to not properly detect the situation. To confirm this, can you please attach the saved variables for both addons? You can find them at `wow/WTF/Account/<your account>/SavedVariables/tdBattlePetScript.lua` and `.../Rematch.lua` respectively.
