### ISSUE TITLE
1x tdBattlePetScript/Extension/Round.lua:38: attempt to index field 'rounds' (a nil value)

### ISSUE THREAD

**Issue by BigFire321** [axc450/pbs#78]
1x tdBattlePetScript/Extension/Round.lua:38: attempt to index field 'rounds' (a nil value)
[string "@tdBattlePetScript/Extension/Round.lua"]:38: in function `OnBattleStart'
[string "@tdBattlePetScript/Core/Manager/BattleCacheManager.lua"]:40: in function `?'
[string "@ActionBarSaverReloaded/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...ded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@ActionBarSaverReloaded/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...ded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@ActionBarSaverReloaded/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@ActionBarSaverReloaded/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...nBarSaverReloaded/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:367
 Enable = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 EnableModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 GetName = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:279
 name = "tdBattlePetScript_BattleCacheManager_Round"
 PET_BATTLE_PET_ROUND_RESULTS = <function> defined @tdBattlePetScript/Extension/Round.lua:20
 IsEnabled = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:350
 OnBattleStart = <function> defined @tdBattlePetScript/Extension/Round.lua:37
 RegisterMessage = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 IsModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:217
 SetDefaultModuleState = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:387
 GetRoundByOwner = <function> defined @tdBattlePetScript/Extension/Round.lua:47
 SetEnabledState = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:424
 baseName = "tdBattlePetScript"
 enabledState = true
 GetRound = <function> defined @tdBattlePetScript/Extension/Round.lua:43
 RegisterEvent = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 SendMessage = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 SetDefaultModulePrototype = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:409
 OnEnable = <function> defined @tdBattlePetScript/Extension/Round.lua:9
 IterateModules = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:437
 NewModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:235
 defaultModuleState = true
 PET_BATTLE_PET_CHANGED = <function> defined @tdBattlePetScript/Extension/Round.lua:31
 moduleName = "Round"
 UnregisterEvent = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 Disable = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:314
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'rounds' (a nil value)"

[string "@tdBattlePetScript/Extension/Round.lua"]:38: in function `OnBattleStart'
[string "@tdBattlePetScript/Core/Manager/BattleCacheManager.lua"]:40: in function `?'
[string "@ActionBarSaverReloaded/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...ded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@ActionBarSaverReloaded/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...ded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@ActionBarSaverReloaded/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@ActionBarSaverReloaded/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...nBarSaverReloaded/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:367
 Enable = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:294
 UnregisterAllEvents = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 EnableModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 GetName = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:279
 name = "tdBattlePetScript_BattleCacheManager_Round"
 PET_BATTLE_PET_ROUND_RESULTS = <function> defined @tdBattlePetScript/Extension/Round.lua:20
 IsEnabled = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 DisableModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:350
 OnBattleStart = <function> defined @tdBattlePetScript/Extension/Round.lua:37
 RegisterMessage = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 IsModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:217
 SetDefaultModuleState = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:387
 GetRoundByOwner = <function> defined @tdBattlePetScript/Extension/Round.lua:47
 SetEnabledState = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:424
 baseName = "tdBattlePetScript"
 enabledState = true
 GetRound = <function> defined @tdBattlePetScript/Extension/Round.lua:43
 RegisterEvent = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 SendMessage = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 SetDefaultModulePrototype = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:409
 OnEnable = <function> defined @tdBattlePetScript/Extension/Round.lua:9
 IterateModules = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:437
 NewModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:235
 defaultModuleState = true
 PET_BATTLE_PET_CHANGED = <function> defined @tdBattlePetScript/Extension/Round.lua:31
 moduleName = "Round"
 UnregisterEvent = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 Disable = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:314
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'rounds' (a nil value)"

1x tdBattlePetScript_Rematch/Addon.lua:21: attempt to index global 'RematchSettings' (a nil value)
[string "@tdBattlePetScript_Rematch/Addon.lua"]:21: in function <tdBattlePetScript_Rematch/Addon.lua:20>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `xpcall'
[string "@tdBattlePetScript/Core/Director.lua"]:209: in function `Select'
[string "@tdBattlePetScript/UI/PetBattle.lua"]:278: in function `UpdateScriptList'
[string "@tdBattlePetScript/UI/PetBattle.lua"]:240: in function `?'
[string "@ActionBarSaverReloaded/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...ded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@ActionBarSaverReloaded/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...ded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@ActionBarSaverReloaded/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@ActionBarSaverReloaded/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...nBarSaverReloaded/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:367
 Enable = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:294
 NewModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:235
 EnableModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:442
 SecureHook = <function> defined @Plexus/Libs/AceHook-3.0/AceHook-3.0.lua:335
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @Plexus/Libs/AceHook-3.0/AceHook-3.0.lua:394
 OnDisable = <function> defined @tdBattlePetScript_Rematch/UI.lua:237
 hooks = <table> {
 }
 _title = "Rematch"
 baseName = "tdBattlePetScript_Rematch"
 SetDefaultModulePrototype = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:409
 OnExport = <function> defined @tdBattlePetScript_Rematch/UI.lua:249
 OnImport = <function> defined @tdBattlePetScript_Rematch/UI.lua:256
 IterateKeys = <function> defined @tdBattlePetScript_Rematch/Addon.lua:24
 name = "tdBattlePetScript_PluginManager_Rematch"
 _icon = "Interface\Icons\PetJournalPortrait"
 IsEnabled = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 OnTooltipFormatting = <function> defined @tdBattlePetScript_Rematch/Addon.lua:49
 DisableModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:350
 NewClass = <function> defined @tdBattlePetScript/Libs/tdGUI/Libs/LibClass-2.0/Class-2.0.lua:322
 OnEnable = <function> defined @tdBattlePetScript_Rematch/UI.lua:52
 GetPetTip = <function> defined @tdBattlePetScript_Rematch/Addon.lua:36
 GetTitleByKey = <function> defined @tdBattlePetScript_Rematch/Addon.lua:32
 RegisterMessage = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 FindMenuItem = <function> defined @tdBattlePetScript_Rematch/UI.lua:241
 GetCurrentKey = <function> defined @tdBattlePetScript_Rematch/Addon.lua:20
 IsHooked = <function> defined @Plexus/Libs/AceHook-3.0/AceHook-3.0.lua:492
 OnInitialize = <function> defined @tdBattlePetScript_Rematch/Addon.lua:13
 GetClass = <function> defined @tdBattlePetScript/Libs/tdGUI/Libs/LibClass-2.0/Class-2.0.lua:332
 IsModule = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:217
 _notes = "This script selector will be bound to Rematch team."
 SetDefaultModuleState = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:387
 SendMessage = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 UnhookAll = <function> defined @Plexus/Libs/AceHook-3.0/AceHook-3.0.lua:476
 SetEnabledState = <function> defined @ActionBarSaverReloaded/Libs/AceAddon-3.0/AceAddon-3.0.lua:424
 Hook = <function> defined @Plexus/Libs/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 Unhook = <function> defined @Plexus/Libs/AceHook-3.0/AceHook-3.0.lua:417
 RegisterEvent = <function> defined @ActionBarSaverReloaded/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessag

**Comment by bloerwald** [comment]
Can you give us context as to *when* this happened? Have you by chance reloaded while in a battle?

**Comment by BigFire321** [comment]
I just went ahead and delete both of them and reinstall just the petscript.  It now looks better.
