### ISSUE TITLE
Addon.lua:214: attempt to index field '?' (a function value)

### ISSUE THREAD

**Issue by Ookami313** [axc450/pbs#81]
Running 1.9.3. Tried to import a script from Xu-Fu's and when I go to select the NPC I'm battling (Select the Key), after selecting Rematch from the first dropdown menu, I get the following error and it will not let me continue with the import. Thanks.

16x tdBattlePetScript/Rematch/Addon.lua:214: attempt to index field '?' (a function value)
[string "@tdBattlePetScript/Rematch/Addon.lua"]:214: in function `GetTitleByKey'
[string "@tdBattlePetScript/UI/Import.lua"]:265: in function `menuTable'
[string "@tdBattlePetScript/Libs/tdGUI/Widget/Dropdown.lua"]:124: in function <...Ons/tdBattlePetScript/Libs/tdGUI/Widget/Dropdown.lua:120>
[string "=[C]"]: in function `Click'
[string "@tdBattlePetScript/Libs/tdGUI/Widget/Dropdown.lua"]:41: in function <...Ons/tdBattlePetScript/Libs/tdGUI/Widget/Dropdown.lua:40>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 UnhookAll = <function> defined @BattlePetCompletionist/Libs/AceHook-3.0/AceHook-3.0.lua:476
 Enable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 SecureHookScript = <function> defined @BattlePetCompletionist/Libs/AceHook-3.0/AceHook-3.0.lua:409
 EnableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 _icon = "Interface\AddOns\Rematch\Textures\icon"
 SecureHook = <function> defined @BattlePetCompletionist/Libs/AceHook-3.0/AceHook-3.0.lua:335
 defaultModuleLibraries = <table> {
 }
 hooks = <table> {
 }
 _title = "Rematch"
 baseName = "tdBattlePetScript"
 RawHookScript = <function> defined @BattlePetCompletionist/Libs/AceHook-3.0/AceHook-3.0.lua:394
 TeardownUI = <function> defined @tdBattlePetScript/Rematch/UI.lua:215
 SendMessage = <function> defined @DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 UpdateDBRematch4To5 = <function> defined @tdBattlePetScript/Rematch/Addon.lua:325
 ResetEverything = <function> defined @tdBattlePetScript/Rematch/Addon.lua:318
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 OnImportContinuation = <function> defined @tdBattlePetScript/Rematch/Addon.lua:305
 OnImport = <function> defined @tdBattlePetScript/Rematch/Addon.lua:284
 OnExport = <function> defined @tdBattlePetScript/Rematch/Addon.lua:267
 name = "PetBattleScripts_PluginManager_Rematch"
 OnExportImpl = <function> defined @tdBattlePetScript/Rematch/Addon.lua:256
 IsEnabled = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 OnTooltipFormatting = <function> defined @tdBattlePetScript/Rematch/Addon.lua:220
 DisableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 NewClass = <function> defined @tdBattlePetScript/Libs/tdGUI/Libs/LibClass-2.0/Class-2.0.lua:349
 GetTitleByKey = <function> defined @tdBattlePetScript/Rematch/Addon.lua:210
 IterateKeys = <function> defined @tdBattlePetScript/Rematch/Addon.lua:196
 GetCurrentKey = <function> defined @tdBattlePetScript/Rematch/Addon.lua:186
 RegisterMessage = <function> defined @DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 OnDisable = <function> defined @tdBattlePetScript/Rematch/Addon.lua:167
 OnEnable = <function> defined @tdBattlePetScript/Rematch/Addon.lua:25
 IsHooked = <function> defined @BattlePetCompletionist/Libs/AceHook-3.0/AceHook-3.0.lua:492
 OnInitialize = <function> defined @tdBattlePetScript/Rematch/Addon.lua:14
 GetClass = <function> defined @tdBattlePetScript/Libs/tdGUI/Libs/LibClass-2.0/Class-2.0.lua:359
 IsModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:213
 _notes = "This script selector will be bound to the Rematch team."
 SetDefaultModuleState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:383
 SetupUI = <function> defined @tdBattlePetScript/Rematch/UI.lua:49
 updateFrames = <function> defined @tdBattlePetScript/

**Comment by Ookami313** [comment]
![image](https://github.com/axc450/pbs/assets/26803942/8f7ce4bf-ff01-4bc5-939c-bfbfc1ccf1de)

**Comment by bloerwald** [comment]
- Don't bother using that import dialog. Just right click your team in Rematch and select "create script". That makes it easier to match them as well.
- This should be fixed with v1.10 which was just released.
