### ISSUE TITLE
Only the first line of instructions will be executed.

### ISSUE THREAD

**Issue by logantsai** [axc450/pbs#89]
Rematch: Rematch_5_1_4.zip
Pet Battle Scripts: PetBattleScripts-v1.10.1.zip

When I click the test button multiple times, only the first line of instructions is executed.

Note: I only enable Rematch and Pet Battle Scripts addon, but the problem is the same.
I copy some sample script from https://www.wow-petguide.com/ to double check. The problem is the same.
How should I debug this?

Thanks

**Comment by bloerwald** [comment]
Scripts run from top to bottom every time you press the button. The first action that can be executed based on conditions and cooldowns will win and end the script. I would assume your first line can be executed unconditionally, so it *is* executed unconditionally. 

Care to post the script you're using?

**Comment by logantsai** [comment]
![螢幕擷取畫面 2024-04-07 082614](https://github.com/axc450/pbs/assets/22437089/76539425-6910-48b3-9760-f9cd63fb0fa0)
I use this two skill and only top one will be executed. No idea why the next one didn't be effective

**Comment by bloerwald** [comment]
Ability 1370 has no cooldown and you didn't give it a condition, so it will be always executed, as said. 

I assume your script is supposed to keep 919 debuff active and otherwise spam 1370. To do that, 
```
use(claw:919) [ !enemy.aura(claw debuff:918).exists ]
use(filler:1370)
```
or if you want to have the filler in the first and only first round as well, 
```
use(filler:1370) [ round = 1 ]
use(claw:919) [ !enemy.aura(claw debuff:918).exists ]
use(filler:1370)
```

**Comment by logantsai** [comment]
Thank you for patiently explaining, I understand now, I have no more questions. I really appreciate your help.
