### ISSUE TITLE
Issues on beta - with version 1.10.1

### ISSUE THREAD

**Issue by fraerie** [axc450/pbs#90]
Errors on load into game

3x tdBattlePetScript/Core/Addon.lua:76: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@tdBattlePetScript/Core/Addon.lua"]:76: in function `UpdateDatabase'
[string "@tdBattlePetScript/Core/Addon.lua"]:65: in function <tdBattlePetScript/Core/Addon.lua:61>
[string "=[C]"]: ?
[string "@ItemVersion/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ddOns/ItemVersion/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ItemVersion/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@ItemVersion/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ddOns/ItemVersion/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 baseName = "tdBattlePetScript"
 name = "PetBattleScripts"
 orderedModules = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
}
oldVersion = nil
(*temporary) = nil
(*temporary) = "tdBattlePetScript"
(*temporary) = "Version"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"
ADDON = "tdBattlePetScript"
GUI = <table> {
 Retail = true
 BackdropTemplate = "BackdropTemplate"
 BCC = false
}
ns = <table> {
 Action = <table> {
 }
 ICON = "Interface\Icons\Icon_petfamily_dragon"
 Condition = <table> {
 }
 L = <table> {
 }
 Director = <table> {
 }
 Options = <table> {
 }
 Addon = <table> {
 }
 PluginManager = <table> {
 }
 RematchPlugin = <table> {
 }
 BattleCachePrototype = <table> {
 }
 ScriptManager = <table> {
 }
 Snippets = <table> {
 }
 Version = <table> {
 }
 BattleCacheManager = <table> {
 }
 UI = <table> {
 }
 Stack = <table> {
 }
 Util = <table> {
 }
 PluginPrototype = <table> {
 }
}

================

16x ...Ons/tdBattlePetScript/Core/Manager/PluginManager.lua:188: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@tdBattlePetScript/Core/Manager/PluginManager.lua"]:188: in function <...Ons/tdBattlePetScript/Core/Manager/PluginManager.lua:183>
[string "=(tail call)"]: ?
[string "@tdBattlePetScript/Plugins/Base.lua"]:15: in function <tdBattlePetScript/Plugins/Base.lua:14>
[string "=[C]"]: ?
[string "@ItemVersion/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ddOns/ItemVersion/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ItemVersion/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@ItemVersion/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ddOns/ItemVersion/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 moduleWatings = <table> {
 }
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "PetBattleScripts_PluginManager"
 orderedModules = <table> {
 }
 pluginsOrdered = <table> {
 }
 baseName = "tdBattlePetScript"
 moduleEnableQueue = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 moduleName = "PluginManager"
}
module = <table> {
 requiredAddon = "Blizzard_PetBattleUI"
 baseName = "tdBattlePetScript"
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabledState = false
 moduleName = "Base"
 defaultModuleState = true
 name = "PetBattleScripts_PluginManager_Base"
 orderedModules = <table> {
 }
}
addon = "Blizzard_PetBattleUI"
(*temporary) = nil
(*temporary) = "Blizzard_PetBattleUI"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"

**Comment by GurliGebis** [comment]
I think the `GetAddOnMetadata` function has been moved into `C_AddOn` - I'm unable to test it right now, but it might point someone in the right direction.
