### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by CSN701** [axc450/pbs#93]
With the new update to WoW the script add on doesn't seem to be working. The add on is installed and shows in my add on list but unable to use any functions in or out of pet battles.

**Comment by DistractionCzar** [comment]
I can verify this, the option to add or modify the script does not appear
![image](https://github.com/user-attachments/assets/deb300ad-141b-4fae-b678-7932c66932ac)

**Comment by ivikatasha** [comment]
Here is my bug report

24x ...Ons/tdBattlePetScript/Core/Manager/PluginManager.lua:188: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@tdBattlePetScript/Core/Manager/PluginManager.lua"]:188: in function <...Ons/tdBattlePetScript/Core/Manager/PluginManager.lua:183>
[string "=(tail call)"]: ?
[string "@tdBattlePetScript/Plugins/Base.lua"]:15: in function <tdBattlePetScript/Plugins/Base.lua:14>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 moduleWatings = <table> {
 }
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "PetBattleScripts_PluginManager"
 orderedModules = <table> {
 }
 pluginsOrdered = <table> {
 }
 baseName = "tdBattlePetScript"
 moduleEnableQueue = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 moduleName = "PluginManager"
}
module = <table> {
 requiredAddon = "Blizzard_PetBattleUI"
 baseName = "tdBattlePetScript"
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabledState = false
 moduleName = "Base"
 defaultModuleState = true
 name = "PetBattleScripts_PluginManager_Base"
 orderedModules = <table> {
 }
}
addon = "Blizzard_PetBattleUI"
(*temporary) = nil
(*temporary) = "Blizzard_PetBattleUI"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"

**Comment by fraerie** [comment]
Confirming - running PetBattleScripts-v1.10 in WoW Patch 11.0.2.56011 I am getting the following error on load into game:

1x tdBattlePetScript/Core/Version.lua:21: attempt to call global 'GetAddOnEnableState' (a nil value)
[string "@tdBattlePetScript/Core/Version.lua"]:21: in function `Current'
[string "@tdBattlePetScript/Core/Addon.lua"]:76: in function `UpdateDatabase'
[string "@tdBattlePetScript/Core/Addon.lua"]:65: in function <tdBattlePetScript/Core/Addon.lua:61>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventoryClient.lua"]:935: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13471: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13494: in function `BlizzardAPIHook'
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
self = <table> {
 _Meta = <table> {
 }
}
addon = "tdBattlePetScript"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "tdBattlePetScript"
(*temporary) = "attempt to call global 'GetAddOnEnableState' (a nil value)"
Version = <table> {
 _Meta = <table> {
 }
}

**Comment by fraerie** [comment]
Also getting:

2x ...Ons/tdBattlePetScript/Core/Manager/PluginManager.lua:188: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@tdBattlePetScript/Core/Manager/PluginManager.lua"]:188: in function <...Ons/tdBattlePetScript/Core/Manager/PluginManager.lua:183>
[string "=(tail call)"]: ?
[string "@tdBattlePetScript/Plugins/Base.lua"]:15: in function <tdBattlePetScript/Plugins/Base.lua:14>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 moduleWatings = <table> {
 }
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "PetBattleScripts_PluginManager"
 orderedModules = <table> {
 }
 pluginsOrdered = <table> {
 }
 baseName = "tdBattlePetScript"
 moduleEnableQueue = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 moduleName = "PluginManager"
}
module = <table> {
 requiredAddon = "Blizzard_PetBattleUI"
 baseName = "tdBattlePetScript"
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabledState = false
 moduleName = "Base"
 defaultModuleState = true
 name = "PetBattleScripts_PluginManager_Base"
 orderedModules = <table> {
 }
}
addon = "Blizzard_PetBattleUI"
(*temporary) = nil
(*temporary) = "Blizzard_PetBattleUI"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"

**Comment by swotam** [comment]
Getting the following after loading into the game:

48x ...Ons/tdBattlePetScript/Core/Manager/PluginManager.lua:188: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@tdBattlePetScript/Core/Manager/PluginManager.lua"]:188: in function <...Ons/tdBattlePetScript/Core/Manager/PluginManager.lua:183>
[string "=(tail call)"]: ?
[string "@tdBattlePetScript/Plugins/Base.lua"]:15: in function <tdBattlePetScript/Plugins/Base.lua:14>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 moduleWatings = <table> {
 }
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "PetBattleScripts_PluginManager"
 orderedModules = <table> {
 }
 pluginsOrdered = <table> {
 }
 baseName = "tdBattlePetScript"
 moduleEnableQueue = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 moduleName = "PluginManager"
}
module = <table> {
 requiredAddon = "Blizzard_PetBattleUI"
 baseName = "tdBattlePetScript"
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabledState = false
 moduleName = "Base"
 defaultModuleState = true
 name = "PetBattleScripts_PluginManager_Base"
 orderedModules = <table> {
 }
}
addon = "Blizzard_PetBattleUI"
(*temporary) = nil
(*temporary) = "Blizzard_PetBattleUI"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"

-----

12x tdBattlePetScript/Core/Version.lua:21: attempt to call global 'GetAddOnEnableState' (a nil value)
[string "@tdBattlePetScript/Core/Version.lua"]:21: in function `Current'
[string "@tdBattlePetScript/Core/Addon.lua"]:76: in function `UpdateDatabase'
[string "@tdBattlePetScript/Core/Addon.lua"]:65: in function <tdBattlePetScript/Core/Addon.lua:61>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Rarity/Core/Collections.lua"]:63: in function `ScanToys'
[string "@Rarity/Core/Collections.lua"]:282: in function `ScanExistingItems'
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
self = <table> {
 _Meta = <table> {
 }
}
addon = "tdBattlePetScript"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "tdBattlePetScript"
(*temporary) = "attempt to call global 'GetAddOnEnableState' (a nil value)"
Version = <table> {
 _Meta = <table> {
 }
}

**Comment by nerzhul** [comment]
i can confirm the same issue, it seems broken since 11.0.2
